// The engines' bulk tables are generated by our own code (formulas, key colours), not copied from the
// DLLs. Each must still be, byte for byte, the table the port shipped before (and that its runs were
// proven exact with, docs/EXACTNESS.md). The expected values are sha256 hashes of those original bytes.
import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { A } from '../../src/engine/ns';
import { ATN_HI, ATN_LO, tpiTable } from '../../src/engine/rand';
import '../../src/engine/effect';
import { T_exp, T_lin, T_mant } from '../../src/engine/bars';
import '../../src/engine/battery/index';
import { PALS } from '../../src/engine/ambience/index';

const sha = (a: ArrayBufferView) => createHash('sha256').update(new Uint8Array(a.buffer, a.byteOffset, a.byteLength)).digest('hex');

describe('generated tables equal the originals', () => {
  it('Bars and Waves: T_lin, T_mant, T_exp', () => {
    expect(sha(T_lin)).toBe('2b63ec6dee1cad51b2ca2e4b2af3ee727af89334aae9d5919cdab9009f08bdb3');
    expect(sha(T_mant)).toBe('51e77e1c11a0cd0d729f6f26e09ee629bc357773219d68255027a8393c9dad74');
    expect(sha(T_exp)).toBe('b079b34242bebb0357bf3c794f14bc2315399d09bfb99f2f9c3e761519a0b347');
  });

  it("ucrtbase's atan(i/256) hi/lo table and 2/pi bits", () => {
    expect(sha(ATN_HI)).toBe('ecf529f093f2b910cef5928054f1789b94965173f0823085a70e8a350ddfbc2d');
    expect(sha(ATN_LO)).toBe('04562e7936c39ce19e9586f15f81bed6aaa9a9f34ed3893dd384b24df7fbc9a8');
    expect(sha(tpiTable())).toBe('ac7ecc255c7e132d60263a2b29327878504695834f3afe2a2c5cf3d37874ef57');
  });

  it("Battery's stored palettes, as LoadFromRegistry hands them to TO", () => {
    const I = (A.Battery as unknown as { internals: { PRESETS: [string, ...unknown[]][]; presetPalette: (p: string) => Uint8Array } }).internals;
    const want: Record<string, string> = {
      circledance: 'ec366cb113f8d8343fa3c497f89774220e82ac681662d7ed7f4f60188a454689',
      cominatya: '71d8a0847e73f316d0a535cf9e3531fb279039bb6f9329fe4d03ec82e93e287c',
      dandelionaid: '491380eb79bc53a10cce194962c1dea717a998613fce1f77104e87ec78a2b365',
      DrowningFlower: '84dfb929ae72876a60524dea57a8e54b9bac5c83c847c1ec2a303a240a2e4363',
      EletriArnation: '862c230db9191675e45d274bd7170dea313b1f110ab8564c3200090d147565be',
      'Geeks Kick ASCII': '26009f9f0b231a6756138c88a6e2faef55fa7b71de553f590e000d14d8e17368',
      'gemstone matrix': '4aa1ec721091eddf94d203b0fba3853e88045e3a2ef28c285f999848695a3d42',
      GrooveSwirl: '467e9204d499df9758287d93d640668be97e78ae9ad2ae694306c3d3d787b6c2',
      ISeeTheTruth: '1c45774de2fd91e954e57041dfc2d68430311beff43215894936913f76fddcdb',
      khemicalnova: '359ef5e799bb39a8772acda711497176c46bc81d121732903a3aa04a17561787',
      Lotus: '93122b51b3414cacd04aedce3fc9b694a3a6e456545834e84d6639e94e92e582',
      'Nerds Are Cool': '1c45774de2fd91e954e57041dfc2d68430311beff43215894936913f76fddcdb',
      relativelycalm: '80b5086348674d4003599c5b518d543d9b9ef654a7fa2940da3c81f0ea7c50ac',
      'Smoke or Water': '10dbfb176e27fb0d20c29e17d1c24f256514b112dccddc1a66ac9c74242c0b9e',
      SpidersLastMoment: '1c45774de2fd91e954e57041dfc2d68430311beff43215894936913f76fddcdb',
      strawberryaid: '9e4b235974c6c1b744222c674ed62ff712282c0168d1f824a0439976f05ba4e7',
      'the world': 'c2ab72b39c821a94e5b1f0d168628ba8f5dea03a00be7f3e31ec0bf05dbaf44a',
    };
    const got: Record<string, string> = {};
    for (const p of I.PRESETS) if (p[8]) got[p[0]] = sha(I.presetPalette(p[8] as string));
    expect(got).toEqual(want);
  });

  it("Ambience's 26 colour sets", () => {
    expect(sha(PALS)).toBe('7710e423821f259366159816371da8a257106f3cb830c46f0de63dcf59fab632');
  });
});
