// npm run build:wasm            compile each AssemblyScript kernel below and write the module,
//                               base64, into its src/engine/*-wasm.ts
// node tools/build-wasm.mjs --check
//                               exit 1 if a file is not what its source compiles to now
//                               (tests/engine/movebits.test.ts runs this, so npm test catches drift)
// The generated file is committed: the page, the Spotify bundle, dist/engine.js, vitest and tsc all
// import it as a plain string, so none of them needs AssemblyScript or a build step.
import asc from 'assemblyscript/asc';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FLAGS = ['-O3', '--noAssert', '--runtime', 'stub', '--enable', 'simd'];
const KERNELS = [
  { src: 'assembly/movebits.ts', out: 'src/engine/movebits-wasm.ts', name: 'MOVEBITS_WASM' },
  { src: 'assembly/battery.ts', out: 'src/engine/battery/kernel-wasm.ts', name: 'BATTERY_WASM' },
  { src: 'assembly/trig.ts', out: 'src/engine/trig-wasm.ts', name: 'TRIG_WASM' },
];

let stale = false;
for (const { src, out, name } of KERNELS) {
  let wasm = null;
  const { error, stderr } = await asc.main([src, ...FLAGS, '--outFile', 'out.wasm'], {
    stdout: asc.createMemoryStream(),
    stderr: asc.createMemoryStream(),
    readFile: (f, baseDir) => { try { return readFileSync(join(ROOT, baseDir, f), 'utf8'); } catch { return null; } },
    writeFile: (f, contents) => { if (f.endsWith('.wasm')) wasm = contents; },
    listFiles: () => [],
  });
  if (error || !wasm) {
    console.error(stderr.toString());
    console.error(error ? error.message : 'no .wasm produced');
    process.exit(1);
  }

  const text = `// Generated by \`npm run build:wasm\` (tools/build-wasm.mjs) from ${src}: do not edit.
// AssemblyScript ${asc.version}, ${FLAGS.join(' ')}; ${wasm.length} bytes.
export const ${name} =
  '${Buffer.from(wasm).toString('base64')}';
`;

  if (process.argv.includes('--check')) {
    let cur = '';
    try { cur = readFileSync(join(ROOT, out), 'utf8'); } catch { /* missing counts as stale */ }
    if (cur !== text) { console.error(`${out} is not what ${src} compiles to: run npm run build:wasm`); stale = true; }
    else console.log(`${out} is current (${wasm.length} bytes)`);
  } else {
    writeFileSync(join(ROOT, out), text);
    console.log(`wrote ${out} (${wasm.length} bytes of wasm)`);
  }
}
if (stale) process.exit(1);
