// npm run build:wasm            compile assembly/movebits.ts (AssemblyScript) and write the module,
//                               base64, into src/engine/movebits-wasm.ts
// node tools/build-wasm.mjs --check
//                               exit 1 if that file is not what the source compiles to now
//                               (tests/engine/movebits.test.ts runs this, so npm test catches drift)
// The generated file is committed: the page, the Spotify bundle, dist/engine.js, vitest and tsc all
// import it as a plain string, so none of them needs AssemblyScript or a build step.
import asc from 'assemblyscript/asc';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src/engine/movebits-wasm.ts');
const FLAGS = ['-O3', '--noAssert', '--runtime', 'stub', '--enable', 'simd'];

let wasm = null;
const { error, stderr } = await asc.main(['assembly/movebits.ts', ...FLAGS, '--outFile', 'movebits.wasm'], {
  stdout: asc.createMemoryStream(),
  stderr: asc.createMemoryStream(),
  readFile: (name, baseDir) => { try { return readFileSync(join(ROOT, baseDir, name), 'utf8'); } catch { return null; } },
  writeFile: (name, contents) => { if (name.endsWith('.wasm')) wasm = contents; },
  listFiles: () => [],
});
if (error || !wasm) {
  console.error(stderr.toString());
  console.error(error ? error.message : 'no .wasm produced');
  process.exit(1);
}

const text = `// Generated by \`npm run build:wasm\` (tools/build-wasm.mjs) from assembly/movebits.ts: do not edit.
// AssemblyScript ${asc.version}, ${FLAGS.join(' ')}; ${wasm.length} bytes.
export const MOVEBITS_WASM =
  '${Buffer.from(wasm).toString('base64')}';
`;

if (process.argv.includes('--check')) {
  let cur = '';
  try { cur = readFileSync(OUT, 'utf8'); } catch { /* missing counts as stale */ }
  if (cur !== text) {
    console.error('src/engine/movebits-wasm.ts is not what assembly/movebits.ts compiles to: run npm run build:wasm');
    process.exit(1);
  }
  console.log(`src/engine/movebits-wasm.ts is current (${wasm.length} bytes)`);
} else {
  writeFileSync(OUT, text);
  console.log(`wrote src/engine/movebits-wasm.ts (${wasm.length} bytes of wasm)`);
}
